### ISSUE TITLE
DKMS module incompatible with Linux 6.4.6

### ISSUE THREAD

**Issue by leviport** [pop-os/nvidia-graphics-drivers-470#14]

**Comment by mrmodolo** [comment]
Hi,
After upgrading today `Linux kernel version 6.4.6-76060406-generic #202307241739~1690928105~22.04~d567a38 SMP PREEMPT_DYNAMIC Tue A x86_64 x86_64 x86_64 GNU/Linux` is no longer able to install the nvidia-driver-47 driver due to incompatibility with kernel source code at the time of installing the nvidia-dkms-470 package

**Comment by leviport** [comment]
Yep, that's what this bug report is about.
